### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by ZeroJL7** [sule01u/SBSCAN#1]
python3.8.9版本运行报错，显示
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 116: illegal multibyte sequence

**Comment by sule01u** [comment]
你好：
很高兴你使用我的项目并提出建议；
根据你的反馈我已经使用window平台成功复现并解决，通过读取配置文件时指定utf-8编码来解决这个问题；
请使用git pull拉取最新代码后重新尝试运行项目。

**Comment by sule01u** [comment]
如果未解决问题，欢迎重新打开这个issue并附上详细的报错信息。
