### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

### ISSUE THREAD

**Issue by latxz2025** [sule01u/SBSCAN#12]
<img width="851" alt="Snipaste_2024-03-28_11-51-36" src="https://github.com/sule01u/SBSCAN/assets/52594948/c6deddd3-403f-42b9-a282-549244b10b4f">

**Comment by latxz2025** [comment]
<img width="476" alt="Snipaste_2024-03-28_11-52-49" src="https://github.com/sule01u/SBSCAN/assets/52594948/d7c91061-915e-4fc7-9810-c9916e637b79">

**Comment by latxz2025** [comment]
python -m pip install --upgrade urllib3

**Comment by sule01u** [comment]
> python -m pip install --upgrade urllib3

解决你的问题了吗

**Comment by latxz2025** [comment]
解决了
&nbsp;


流泪的土豆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月29日(星期五) 上午10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sule01u/SBSCAN] ModuleNotFoundError: No module named &#39;urllib3.packages.six.moves&#39; (Issue #12)





  
python -m pip install --upgrade urllib3
  
解决你的问题了吗

**Comment by latxz2025** [comment]
解决了
