### ISSUE TITLE
想让数据走BP，添加代理参数报错

### ISSUE THREAD

**Issue by Superhero-zero** [sule01u/SBSCAN#3]
![image](https://github.com/sule01u/SBSCAN/assets/66772820/2a58e627-b5b3-439b-b268-017454dfd9f4)

**Comment by sule01u** [comment]
你好：
很高兴你使用我的项目并给出问题反馈；
根据你的报错信息我已经复现并解决，由于近期格式化项目代码时候将所有请求加上了代理，导致请求代理是否可用的时候也配置了代理选项导致出错；

**解决方案：**
请使用git pull拉取最新代码后重新尝试运行项目。

**Comment by sule01u** [comment]
如果未解决你的问题，欢迎重开打开issue并附上详细的报错信息
