### ISSUE TITLE
windows下终止程序运行反应缓慢

### ISSUE THREAD

**Issue by Superhero-zero** [sule01u/SBSCAN#4]
在终端ctrl+z中止程序运行反应比较缓慢

**Comment by sule01u** [comment]
师傅你好！
**复现:** 今天使用window虚拟机复现了你的问题，window处理信号跟unix的不太一样；
**缓解方案:** 最快的解决方案是 **使用ctrl + break 退出程序** ， 我这边测试是ok的，你可以尝试这个方案看看是否能解决你退出的问题；
