### ISSUE TITLE
下载最新的源码后扫不出靶场漏洞

### ISSUE THREAD

**Issue by Superhero-zero** [sule01u/SBSCAN#5]
![image](https://github.com/sule01u/SBSCAN/assets/66772820/5d9ff942-0837-4462-8a47-18cdb2f8b9e2)

**Comment by sule01u** [comment]
师傅你好：
这两个版本的改动非常小，可能是由于网络问题，你可以再试试

**Comment by Superhero-zero** [comment]
不行的，换了几个网络都是这样，而且最新源码执行的时候回复结果很快，几乎没有延迟。但是从release下载的源码执行结果很明显有个时间过程。这边靶场环境开好了，您可以试下两个不同的源码同样的命令结果

**Comment by sule01u** [comment]
已更新，师傅同步一下最新代码看看，不过我没有检测到你图中所示的漏洞，漏洞路径返回状态码是502

**Comment by Superhero-zero** [comment]
感谢，经测试最新源码已经能够正常探测靶场漏洞并使用其代理功能，师傅在提一个建议，能不能给个扫描参数，因为该程序目前扫描是先扫敏感目录在做漏洞探测，能不能出一个针对于这个问题的单独参数，比如-s a 只做敏感目录扫描 -s b 只做漏洞检测
因为有时候只想看下漏洞探测这块的数据包，不需要看敏感目录扫描那块

**Comment by sule01u** [comment]
非常感谢师傅积极的反馈和建议！我非常认同你提出的这个功能需求，这样确实可以让用户更加灵活地使用工具。

我已经记录下来，将考虑在后续版本中进行支持，请保持关注，后续更新会尽快推出。
