### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by majq1990** [sule01u/SBSCAN#9]
ERROR: Could not find a version that satisfies the requirement charset-normalizer==3.3.0 (from versions: 0.1a0, 0.1.1a0, 0.1.2b0, 0
.1.4b0, 0.1.5b0, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.4.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.1.0, 2.1.1, 3.0.0b1, 3.0.0b2, 3.0.0rc1, 3.0.0, 3.0.1)

**Comment by sule01u** [comment]
师傅你好：
你的报错信息显示版本错误，你的仓库源应该还没有更新到这个版本，你安装的时候是指定的清华源吗？
你可以使用： pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple   指定安装源

**Comment by majq1990** [comment]
我的环境：Python 3.6.8   
pip        21.3.1

另外操作是指定了清华的源

**Comment by majq1990** [comment]
(sbscan) [root@egova-demo SBSCAN]# python --version
Python 3.6.8
(sbscan) [root@egova-demo SBSCAN]# pip --version
pip 21.3.1 from /opt/SBSCAN/sbscan/lib64/python3.6/site-packages/pip (python 3.6)
(sbscan) [root@egova-demo SBSCAN]# pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple 
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting certifi==2023.7.22
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certif
i-2023.7.22-py3-none-any.whl (158 kB)ERROR: Could not find a version that satisfies the requirement charset-normalizer==3.3.0 (from versions: 0.1a0, 0.1.1a0, 0.1.2b0, 0
.1.4b0, 0.1.5b0, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.4.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.1.0, 2.1.1, 3.0.0b1, 3.0.0b2, 3.0.0rc1, 3.0.0, 3.0.1)ERROR: No matching distribution found for charset-normalizer==3.3.0
(sbscan) [root@egova-demo SBSCAN]#

**Comment by sule01u** [comment]
你可以改一下requirement.txt里面，改成 charset-normalizer==3.0.1    然后试试

**Comment by majq1990** [comment]
好的，我试试，谢谢

**Comment by majq1990** [comment]
确认是我的python版本太老了，不支持最新的pip，我弄一下，谢谢
![image](https://github.com/sule01u/SBSCAN/assets/29979847/e44f517e-10f7-43da-9d19-a5dc5f6d05b1)

**Comment by sule01u** [comment]
好的，欢迎反馈工具使用问题
